# Generated by Django 3.0.8 on 2020-08-03 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('label', models.CharField(max_length=32)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('content', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('time', models.DateField()),
                ('picture', models.ImageField(upload_to='images')),
                ('tui', models.IntegerField()),
                ('click', models.IntegerField()),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article.Type')),
            ],
        ),
    ]
